### ISSUE TITLE
几个月过去了，什么时候能公开模型呢，期待ing

### ISSUE THREAD

**Issue by zxy719** [qiuhuachuan/PsyChat#2]
如题

**Comment by qiuhuachuan** [comment]
非常感谢您对我们那工作的关注和支持。
下星期安排上哈，因为最近忙了点，非常抱歉。

这周又在搞论文投稿的rebuttal，
代码还需要整理一下，敬请期待。

**Comment by qiuhuachuan** [comment]
> 如题

您好，已经更新
https://huggingface.co/qiuhuachuan/PsyChat
